// Generated by CoffeeScript 1.6.3
var Notice, Objective, Phrase, monitor;

Notice = require('notice');

Phrase = require('phrase');

Objective = require('./objective');

monitor = require('./monitor');

module.exports = function(opts, objectiveFn) {
  var Module, error, localopts, missing, required;
  missing = (function() {
    var _i, _len, _ref, _results;
    _ref = ['title', 'uuid', 'description'];
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      required = _ref[_i];
      if (opts[required] != null) {
        continue;
      }
      _results.push(required);
    }
    return _results;
  })();
  if (missing.length > 0) {
    console.log("objective(opts, objectiveFn) requires " + (missing.map(function(p) {
      return "opts." + p;
    }).join(', ')));
    process.exit(1);
  }
  localopts = {
    module: opts.module || '../defaults',
    "class": opts["class"] || 'Develop'
  };
  try {
    Module = require(localopts.module);
    if (Module[localopts["class"]] == null) {
      throw new Error("Could not initialize objective module(=" + localopts.module + ") does not define class(=" + localopts["class"] + ")");
    }
    Objective = Module[localopts["class"]];
  } catch (_error) {
    error = _error;
    try {
      delete opts.listen.secret;
    } catch (_error) {}
    try {
      delete opts.listening;
    } catch (_error) {}
    console.log({
      OPTS: opts,
      ERROR: error
    });
    process.exit(2);
  }
  return Notice.listen("objective/" + opts.uuid, opts, function(error, realizerHub) {
    var event, objective, objectiveRecursor, _i, _len, _ref, _results;
    if (error != null) {
      try {
        delete opts.listen.secret;
      } catch (_error) {}
      try {
        delete opts.listening;
      } catch (_error) {}
      console.log({
        OPTS: opts,
        ERROR: error
      });
      process.exit(3);
    }
    objectiveRecursor = void 0;
    realizerHub.use(function(msg, next) {
      console.log(msg.content);
      return next();
    });
    objective = new Objective;
    objective.configure(opts, function() {
      try {
        objectiveRecursor = Phrase.createRoot(opts, function(objectiveToken, objectiveNotice) {
          objectiveNotice.use(function(msg, next) {
            switch (msg.context.title) {
              case 'phrase::link:directory':
                monitor({
                  directory: msg.directory,
                  match: msg.match,
                  ref: 'linked'
                });
                return next();
              case 'phrase::boundry:assemble':
                return objective.onBoundryAssemble(msg.opts, function(error, phrase) {
                  msg.phrase = phrase;
                  msg.error = error;
                  return next();
                });
              case 'phrase::recurse:end':
                console.log({
                  LOADED_PHRASE: msg
                });
                return next();
            }
            console.log('IGNORED:', msg.context.title);
            return next();
          });
          return objectiveToken.on('ready', function(_arg) {
            var tokens;
            tokens = _arg.tokens;
            return objective.startMonitor(opts, monitor, tokens, function(token, opts) {
              return objectiveToken.run(token, opts);
            });
          });
        });
        return objectiveRecursor('objective', objectiveFn || objective.defaultObjective);
      } catch (_error) {
        error = _error;
        try {
          delete opts.listen.secret;
        } catch (_error) {}
        try {
          delete opts.listening;
        } catch (_error) {}
        console.log({
          OPTS: opts,
          ERROR: error
        });
        return process.exit(4);
      }
    });
    _ref = ['create', 'delete'];
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      event = _ref[_i];
      _results.push((function(event) {
        return monitor.dirs.on(event, function(filename, stats, ref) {
          if (ref !== 'linked') {
            return;
          }
          return objectiveRecursor('objective', objectiveFn || objective.defaultObjective);
        });
      })(event));
    }
    return _results;
  });
};
