// Generated by CoffeeScript 1.6.3
var DirectoryMonitor, EventEmitter, Hound, monitor,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

EventEmitter = require('events').EventEmitter;

Hound = require('hound');

DirectoryMonitor = (function(_super) {
  __extends(DirectoryMonitor, _super);

  function DirectoryMonitor() {
    this.monitors = {};
  }

  DirectoryMonitor.prototype.add = function(dirname, match) {
    var event, watch, _i, _len, _ref, _results,
      _this = this;
    if (this.monitors[dirname] == null) {
      this.monitors[dirname] = watch = Hound.watch(dirname);
      _ref = ['create', 'change', 'delete'];
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        event = _ref[_i];
        _results.push((function(event) {
          return watch.on(event, function(filename) {
            if (match != null) {
              if (!filename.match(match)) {
                return;
              }
            }
            return _this.emit(event, filename);
          });
        })(event));
      }
      return _results;
    }
  };

  return DirectoryMonitor;

})(EventEmitter);

module.exports = monitor = function(opts) {
  if (opts.directory != null) {
    return monitor.dirs.add(opts.directory, opts.match);
  }
};

monitor.dirs || (monitor.dirs = new DirectoryMonitor);

module.exports.DirectoryMonitor = DirectoryMonitor;
