// Generated by CoffeeScript 1.6.3
var DirectoryMonitor, Hound;

Hound = require('hound');

DirectoryMonitor = (function() {
  function DirectoryMonitor() {
    this.monitors = {};
  }

  DirectoryMonitor.prototype.add = function(directory) {
    if (this.monitors[directory] == null) {
      return this.monitors[directory] = Hound.watch(directory);
    }
  };

  return DirectoryMonitor;

})();

module.exports.DirectoryMonitor = DirectoryMonitor;
