// Generated by CoffeeScript 1.6.3
var DirectoryMonitor;

DirectoryMonitor = (function() {
  function DirectoryMonitor() {
    this.watchers = [];
  }

  return DirectoryMonitor;

})();

module.exports.DirectoryMonitor = DirectoryMonitor;
