// Generated by CoffeeScript 1.6.3
var Objective;

module.exports = Objective = (function() {
  function Objective() {}

  Objective.prototype.configure = function(opts) {};

  Objective.prototype.defaultObjective = function(Signature) {
    return Signature('Title', function(done) {
      this.does = 'nothing';
      return done();
    });
  };

  Objective.prototype.onBoundry = function(params, callback) {
    return console.log('WARNING Objective.startMonitor() undefined override.');
  };

  Objective.prototype.startMonitor = function(opts, jobTokens, jobEmitter) {
    return console.log('WARNING Objective.startMonitor() undefined override.');
  };

  return Objective;

})();
