// Generated by CoffeeScript 1.6.3
var Realizers, defer, spawner;

defer = require('when').defer;

spawner = require('./spawner');

module.exports = new (Realizers = (function() {
  function Realizers() {}

  Realizers.prototype.get = function() {
    var getting;
    getting = defer();
    process.nextTick(function() {
      return getting.resolve('REALIZER');
    });
    return getting.promise;
  };

  return Realizers;

})());
