// Generated by CoffeeScript 1.4.0
var Coffee, fs, hound;

fs = require('fs');

hound = require('hound');

module.exports = Coffee = (function() {

  function Coffee(program) {
    var app, dir;
    this.program = program;
    try {
      dir = fs.lstatSync('./lib');
      if (dir.isDirectory) {
        app = './lib';
      }
    } catch (_error) {}
    try {
      dir = fs.lstatSync('./app');
      if (dir.isDirectory) {
        if (app) {
          console.log('Appologies. Supports ./app OR ./lib dirs. Not both.');
          return;
        }
        app = './app';
      }
    } catch (_error) {}
    this.config = {
      spec: this.program.specdir || './spec',
      src: this.program.srcdir || './src',
      app: app || './app'
    };
  }

  Coffee.prototype.start = function() {
    console.log("running config:", this.config);
    this.watch('spec', this.onchange);
    return this.watch('src', this.onchange);
  };

  Coffee.prototype.watch = function(what, onchange) {
    var watcher,
      _this = this;
    console.log('Watching: ', this.config[what]);
    watcher = hound.watch(this.config[what]);
    return watcher.on('change', function(file, stats) {
      return onchange.call(_this, what, file, stats);
    });
  };

  Coffee.prototype.onchange = function(what, file, stats) {
    var _this = this;
    switch (what) {
      case 'spec':
        return this.test(file);
      case 'src':
        return this.compile(file, function() {
          return _this.test(_this.toSpec(file));
        });
      case 'app':
        return this.test(this.toSpec(file));
    }
  };

  Coffee.prototype.compile = function(file, after) {
    console.log('pending compile:', file);
    return after();
  };

  Coffee.prototype.toSpec = function(file) {
    console.log('pending convert to specfilename:', file);
    return 'specfilename';
  };

  Coffee.prototype.test = function(file) {
    return console.log('pending run spec:', file);
  };

  return Coffee;

})();
