// Generated by CoffeeScript 1.4.0
var Coffee, Js,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Coffee = require('./coffee');

module.exports = Js = (function(_super) {

  __extends(Js, _super);

  function Js() {
    return Js.__super__.constructor.apply(this, arguments);
  }

  Js.prototype.start = function() {
    this.watch('spec', this.onchange);
    return this.watch('app', this.onchange);
  };

  return Js;

})(Coffee);
