// Generated by CoffeeScript 1.4.0
var ActiveNode, Defaults, Http, Injector, Plex, PluginLoader, Runtime;

Defaults = require('./defaults');

PluginLoader = require('./plugin_loader');

Injector = require('nezcore').injector;

Runtime = require('./exec/nez').exec;

Http = require('http');

Plex = require('plex');

module.exports = ActiveNode = (function() {

  function ActiveNode(label, config, injectable) {
    var match, nodeID, tags,
      _this = this;
    this.label = label;
    this.config = config;
    this.injectable = injectable;
    this.outerValidate();
    nodeID = process.env.NODE_ID;
    tags = process.env.NODE_TAGS || '';
    if (typeof this.config.as === 'string') {
      try {
        if (match = this.config.as.match(/^(.*):(.*)$/)) {
          this.config.as = require(match[1])[match[2]];
        } else {
          this.config.as = require(this.config.as);
        }
      } catch (error) {
        console.log("[ActiveNode] - FAILED to configure as '" + this.config.as + "'");
        throw error;
      }
    }
    this.config.as(nodeID, tags.split(' '), function(activeConfig) {
      _this.innerValidate(activeConfig);
      return _this.start(activeConfig);
    });
  }

  ActiveNode.prototype.start = function(activeConfig) {
    var server, stack,
      _this = this;
    console.log('START:', JSON.stringify(activeConfig, null, 2));
    server = Http.createServer();
    server.listen(20202, 'localhost', function() {
      return console.log('[ActiveNode] - listening @ %s:%s', server.address().address, server.address().port);
    });
    activeConfig._objective.proxy.listen.server = server;
    this.config._class = activeConfig._objective["class"];
    this.plugin = PluginLoader.load(this.config);
    activeConfig._objective.proxy.protocol = this.plugin.bind;
    stack = require('./nez').link();
    stack.name = this.label;
    this.context = Plex.start(activeConfig._objective.proxy);
    Runtime(this.label, this.config);
    if (typeof this.injectable === 'function') {
      return Injector.inject([stack.stacker], this.injectable);
    }
  };

  ActiveNode.prototype.innerValidate = function(config) {};

  ActiveNode.prototype.outerValidate = function() {
    if (typeof this.label !== 'string') {
      throw new Error("ActiveNode requires 'label' string as arg1");
    }
    if (typeof this.config !== 'object') {
      throw new Error("ActiveNode requires config hash as arg2");
    }
    if (typeof this.config.as === 'undefined') {
      this.config.as = process.env.NODE_AS || Defaults['Develop'];
    }
    if (typeof this.injectable !== 'function') {
      throw new Error("ActiveNode requires injectable function arg3");
    }
  };

  return ActiveNode;

})();
