// Generated by CoffeeScript 1.4.0
var ActiveNode, Defaults, Plex;

Defaults = require('./defaults');

Plex = require('plex');

module.exports = ActiveNode = (function() {

  function ActiveNode(label, config, injectable) {
    var nodeID, tags,
      _this = this;
    this.label = label;
    this.config = config;
    this.injectable = injectable;
    this.outerValidate();
    nodeID = process.env.NODE_ID;
    tags = process.env.NODE_TAGS || '';
    this.config._as(nodeID, tags.split(' '), function(activeConfig) {
      _this.innerValidate(activeConfig);
      return _this.start(activeConfig);
    });
  }

  ActiveNode.prototype.start = function(activeConfig) {
    return console.log('START:', JSON.stringify(activeConfig, null, 2));
  };

  ActiveNode.prototype.innerValidate = function(config) {};

  ActiveNode.prototype.outerValidate = function() {
    if (typeof this.label !== 'string') {
      throw new Error("ActiveNode requires 'label' string as arg1");
    }
    if (typeof this.config !== 'object') {
      throw new Error("ActiveNode requires config hash as arg2");
    }
    if (typeof this.config.as === 'undefined') {
      if (typeof this.config._as !== 'function') {
        throw new Error("ActiveNode requires behaviour definition in config._as");
      }
    } else {
      if (typeof Defaults[this.config.as] === 'undefined') {
        throw new Error("ActiveNode as '" + this.config.as + "' is not defined");
      }
      this.config._as = Defaults[this.config.as];
    }
    if (typeof this.injectable !== 'function') {
      throw new Error("ActiveNode requires injectable function arg3");
    }
  };

  return ActiveNode;

})();
