// Generated by CoffeeScript 1.4.0
var Confirmation, Expectation, Realizer, Validation;

require('fing');

Expectation = require('./expectation');

Validation = require('./validation');

Realizer = require('./realizer');

Confirmation = (function() {

  function Confirmation(object, configuration) {
    console.log("new confirmation", arguments);
    this.pending = true;
    this.expectation = new Expectation(object, configuration);
    this.validation = new Validation(this.expectation);
  }

  return Confirmation;

})();

module.exports = Confirmation;
