// Generated by CoffeeScript 1.4.0
var Confirmation, Expectation, Validation;

Expectation = require('./expectation');

Validation = require('./validation');

Confirmation = (function() {

  function Confirmation(object, configuration) {
    var key;
    for (key in configuration) {
      if (key === 'expectation') {
        this.pending = true;
        this.validation = new Validation(new Expectation(object, configuration[key]));
      }
    }
  }

  Confirmation.prototype.validate = function(failedArray) {
    return this.validation.validate(failedArray);
  };

  return Confirmation;

})();

module.exports = Confirmation;
