// Generated by CoffeeScript 1.4.0
var config;

config = require('nezcore').config;

module.exports = {
  Develop: function(id, tags, callback) {
    return callback(null, {
      _objective: {
        "class": 'eo:Develop'
      },
      _plex: {
        secret: 'SEEKRIT'
      }
    });
  },
  SpecRun: function(id, tags, callback) {
    return callback(null, {
      _realizer: {
        "class": 'ipso:SpecRun'
      },
      _plex: {
        secret: 'SEEKRIT'
      }
    });
  }
};
