// Generated by CoffeeScript 1.4.0
var config;

config = require('nezcore').config;

module.exports = {
  Develop: function(id, tags, callback) {
    return callback({
      _objective: {
        "class": 'eo:Develop',
        plex: {
          secret: config.get('secret'),
          connect: {
            adaptor: config.get('adaptor'),
            uri: config.get('home')
          },
          listen: {
            adaptor: config.get('adaptor')
          }
        }
      }
    });
  },
  SpecRun: function(id, tags, callback) {
    return callback({
      _realizer: {
        "class": 'ipso:SpecRun',
        plex: {
          secret: config.get('secret'),
          connect: {
            adaptor: config.get('adaptor'),
            uri: 'http://localhost:20202'
          }
        }
      }
    });
  }
};
