// Generated by CoffeeScript 1.4.0
var Expectation, Realization,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Realization = require('./realization');

module.exports = Expectation = (function(_super) {

  __extends(Expectation, _super);

  function Expectation() {
    return Expectation.__super__.constructor.apply(this, arguments);
  }

  return Expectation;

})(Realization);
