// Generated by CoffeeScript 1.4.0
var AssertionError, Expectation;

AssertionError = require('assert').AssertionError;

Expectation = (function() {

  function Expectation(object, configuration) {
    this.validate(configuration);
    this.configuration.on = object;
  }

  Expectation.prototype.validate = function(configuration) {
    var count, key, name;
    this.configuration = {};
    if (typeof configuration === 'undefined') {
      throw new AssertionError({
        message: 'undefined Expectation configuration'
      });
    }
    if (typeof configuration === 'string') {
      this.configuration[configuration] = {};
      return;
    }
    if (typeof configuration === 'object') {
      if (configuration instanceof Array) {
        throw new AssertionError({
          message: 'Array not a valid Expectation configuration'
        });
      }
    }
    count = 0;
    for (key in configuration) {
      name = key;
      if (++count > 1) {
        throw new AssertionError({
          message: 'Multiple key hash not a valid Expectation configuration'
        });
      }
    }
    return this.configuration = configuration;
  };

  return Expectation;

})();

module.exports = Expectation;
