// Generated by CoffeeScript 1.4.0
var Hooks, hooks;

require('fing');

Hooks = (function() {

  function Hooks(subscribe) {
    subscribe('edge', this.handle);
  }

  Hooks.prototype.set = function(node, config) {
    var key, _results;
    _results = [];
    for (key in config) {
      if (key === 'beforeEach' || key === 'afterEach') {
        node.hooks[key] = config[key];
      }
      if (key === 'beforeAll' || key === 'afterAll') {
        _results.push(node.hooks[key] = config[key]);
      } else {
        _results.push(void 0);
      }
    }
    return _results;
  };

  Hooks.prototype.handle = function(placeholder, nodes) {
    var afterAll, allHook, ancestors, beforeAll, eachHook, node;
    switch (nodes.tree) {
      case 'down':
        node = nodes.from;
        eachHook = 'beforeEach';
        allHook = 'beforeAll';
        break;
      case 'up':
        node = nodes.to;
        eachHook = 'afterEach';
        allHook = 'afterAll';
    }
    if (typeof node.hooks[allHook] !== 'undefined') {
      node.hooks[allHook]();
      delete node.hooks[allHook];
    }
    return;
    ancestors = node.stack.ancestorsOf(node);
    if (nodes.tree === 'down') {
      beforeAll = nodes.from.hooks['beforeAll'];
      if (beforeAll) {
        beforeAll();
        return delete nodes.from.hooks['beforeAll'];
      }
    } else if (nodes.tree === 'up') {
      afterAll = nodes.to.hooks['afterAll'];
      if (afterAll) {
        afterAll();
        return delete nodes.to.hooks['afterAll'];
      }
    }
  };

  return Hooks;

})();

hooks = {};

module.exports = {
  getFor: function(stack) {
    var _name;
    return hooks[_name = stack.fing.ref] || (hooks[_name] = new Hooks(stack.on));
  }
};
