// Generated by CoffeeScript 1.4.0
var Inflection, Injector;

Inflection = require('inflection');

module.exports = Injector = {
  inject: function() {
    var func, key, klass, module;
    for (key in arguments) {
      func = arguments[key];
    }
    klass = arguments[0];
    module = Injector.findModule(klass);
    return func(require(module));
  }
};
