// Generated by CoffeeScript 1.4.0
var CoffeeScript, link;

CoffeeScript = require('coffee-script');

module.exports = link = {
  linker: function(opts) {
    if (typeof opts === 'string') {
      return link.fileLink(opts);
    }
  },
  fileLink: function(fileName) {
    var file, fs, js;
    fs = require('fs');
    if (fileName.match(/^\//)) {
      file = fileName;
    } else {
      file = link.fixPath(fileName);
    }
    js = CoffeeScript.compile(fs.readFileSync(file).toString(), {
      bare: true
    });
    return eval(js);
  },
  fixPath: function(fileName) {
    return "" + fileName + ".coffee";
  }
};
