// Generated by CoffeeScript 1.4.0
var Expectation, Nez, Realization;

Nez = (function() {

  function Nez() {}

  Nez.debug = false;

  Nez.expectArray = [];

  Nez.expectIndex = {};

  Nez.calledArray = [];

  Nez.failedArray = [];

  Nez.test = function(callback) {
    var expectation;
    if (Nez.debug) {
      console.log('\ntest() runs with:', callback, '\n');
    }
    while (Nez.expectArray.length > 0) {
      expectation = Nez.expectArray.shift();
      expectation.obj[expectation.functionName] = expectation.functionOrig;
    }
    Nez.calledArray.length = 0;
    Nez.failedArray.length = 0;
    Nez.expectIndex = {};
    Nez.debug = false;
    return callback();
  };

  return Nez;

}).call(this);

Realization = (function() {

  function Realization(functionName) {
    this.functionName = functionName;
  }

  return Realization;

})();

Expectation = (function() {

  function Expectation(functionName, functionArgs, functionOrig, obj) {
    var _this = this;
    this.functionName = functionName;
    this.functionArgs = functionArgs;
    this.functionOrig = functionOrig;
    this.obj = obj;
    if (Nez.debug) {
      console.log('\nnew expectation', this.functionName, '\n');
    }
    if (this.functionName === 'expectCall') {
      return;
    }
    this.obj[this.functionName] = function() {
      var call;
      if (Nez.debug) {
        console.log('\n', _this.functionName, '() runs\n');
      }
      call = new Realization(_this.functionName);
      return Nez.calledArray.push(call);
    };
  }

  return Expectation;

})();

Object.prototype.expectCall = function(xpect) {
  var fName, x, _results;
  if (Nez.debug) {
    console.log('\n', 'expectCall() to:', xpect, '\n');
  }
  _results = [];
  for (fName in xpect) {
    x = new Expectation(fName, xpect[fName], this[fName], this);
    if (x.functionName === 'expectCall') {
      continue;
    }
    Nez.expectArray.push(x);
    if (!(Nez.expectIndex[fName] instanceof Array)) {
      Nez.expectIndex[fName] = [];
    }
    Nez.expectIndex[fName].push(Nez.expectArray.length - 1);
    if (Nez.debug) {
      _results.push(console.log('\nexpectIndex with: ', Nez.expectIndex, '\n'));
    } else {
      _results.push(void 0);
    }
  }
  return _results;
};

module.exports = Nez;
