// Generated by CoffeeScript 1.4.0
var Inflection, Injector, Nez, Stack, prototypes;

Stack = require('./stack');

prototypes = require('./prototypes');

Injector = require('./injector');

Inflection = require('inflection');

Nez = (function() {

  function Nez() {}

  return Nez;

})();

Object.defineProperty(Nez, 'realize', {
  get: function() {
    return function() {
      var func, key, klass, module, pusher, validator;
      klass = arguments[0];
      for (key in arguments) {
        func = arguments[key];
      }
      module = Injector.findModule(klass);
      pusher = Nez.stacks['0'].pusher;
      validator = pusher;
      return func(require(module), pusher, validator);
    };
  }
});

Object.defineProperty(Nez, 'test', {
  get: function() {
    var name;
    name = '0';
    Nez.create(name);
    prototypes.object.set.expect(name);
    prototypes.object.set.mock();
    return Nez.link(name);
  }
});

Nez.stacks = {};

Nez.create = function(name) {
  return Nez.stacks[name] = new Stack(name);
};

Nez.link = function(name) {
  Nez.create(name);
  Object.defineProperty(Nez.stacks[name].pusher, 'link', {
    get: function() {
      return function() {};
    }
  });
  return Nez.stacks[name].pusher;
};

module.exports = Nez;
