// Generated by CoffeeScript 1.4.0
var Node;

module.exports = Node = (function() {

  function Node(label, opts) {
    var property;
    if (opts == null) {
      opts = {};
    }
    for (property in opts) {
      this[property] = opts[property];
    }
    this.label = label;
    this.hooks = {};
    this.edges = [];
  }

  return Node;

})();
