// Generated by CoffeeScript 1.4.0
var Node;

module.exports = Node = (function() {

  function Node(label, properties) {
    var property;
    if (properties == null) {
      properties = {};
    }
    for (property in properties) {
      this[property] = properties[property];
    }
    this.label = label;
  }

  return Node;

})();
