// Generated by CoffeeScript 1.4.0
var Notifier, events,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

events = require('events');

module.exports = Notifier = (function(_super) {

  __extends(Notifier, _super);

  function Notifier(events) {
    this.events = events;
  }

  Notifier.prototype.on = function(event, callback) {
    if (!this.events[event]) {
      throw new Error('No such event: "' + event + '"');
    }
    Notifier.__super__.on.call(this, event, callback);
    return console.log(this);
  };

  return Notifier;

})(events.EventEmitter);
