// Generated by CoffeeScript 1.6.3
var notice,
  __slice = [].slice;

notice = require('notice');

module.exports = function() {
  var fn, key, options, opts, title;
  title = arguments[0], opts = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
  if (typeof title !== 'string') {
    throw new Error('objective(title, opts...) requires title as string');
  }
  fn = opts[opts.length - 1];
  if (typeof fn !== 'function') {
    throw new Error('objective(title, opts...) requires function as last argument');
  }
  notice = notice.create(title, function(msg, next) {
    console.log(msg.content);
    return next();
  });
  options = {
    title: title
  };
  if (typeof opts[0] !== 'function') {
    for (key in opts[0]) {
      options[key] = opts[0][key];
    }
  }
  notice.event('objective::start', {
    objective: options
  });
  return fn();
};
