// Generated by CoffeeScript 1.4.0
var Objective, PluginLoader;

PluginLoader = require('./plugin_loader');

module.exports = Objective = {
  load: function(opts) {
    var objectiveModule;
    objectiveModule = process.env.NEZ_PLUGIN_OBJECTIVE || 'eo';
    return PluginLoader.load(objectiveModule, opts);
  }
};
