// Generated by CoffeeScript 1.6.3
var eo, notice;

notice = require('notice');

eo = require('eo');

module.exports = function(title, opts, fn) {
  var key, options;
  if (typeof title !== 'string') {
    throw new Error('objective(title, opts, fn) requires title as string');
  }
  if (typeof opts === 'function') {
    fn = opts;
    opts = {};
  }
  if (typeof fn !== 'function') {
    throw new Error('objective(title, opts, fn) requires function as last argument');
  }
  notice = notice.create(title, function(msg, next) {
    return next();
  });
  options = {
    title: title
  };
  for (key in opts) {
    options[key] = opts[key];
  }
  return eo(notice, options, fn);
};
