// Generated by CoffeeScript 1.4.0
var Exception, PluginFactory, Stack;

Stack = require('./stack');

Exception = require('./exception');

module.exports = PluginFactory = {
  load: function(name, config) {
    var plugin, stack;
    plugin = PluginFactory.validate(require(name));
    stack = new Stack(name);
    plugin.configure(stack.stacker, config);
    return stack.stacker;
  },
  validate: function(plugin) {
    if (typeof plugin.configure !== 'function') {
      throw Exception.create('INVALID_PLUGIN', 'Undefined Plugin.configure()');
    }
    return plugin;
  }
};
