// Generated by CoffeeScript 1.4.0
var PluginRegister, handlers, matchers, plugins;

plugins = [];

handlers = {};

matchers = {};

module.exports = PluginRegister = {
  register: function(plugin) {
    var handler, match, _i, _j, _len, _len1, _ref, _ref1;
    _ref = plugin.handles;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      handler = _ref[_i];
      handlers[handler] || (handlers[handler] = []);
      handlers[handler].push(plugins.length);
    }
    _ref1 = plugin.matches;
    for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
      match = _ref1[_j];
      matchers[match] || (matchers[match] = []);
      matchers[match].push(plugins.length);
    }
    plugins.push(plugin);
    return PluginRegister;
  },
  handle: function(node) {
    var addr, handlerFn, handlerFnName, key, plugin, _i, _j, _len, _len1, _ref, _ref1;
    if (typeof handlers[node["class"]] !== 'undefined') {
      handlerFnName = node["class"];
      _ref = handlers[handlerFnName];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        addr = _ref[_i];
        plugin = plugins[addr];
        plugin[handlerFnName](node);
      }
    }
    if (typeof node.label === 'object') {
      for (key in node.label) {
        if (typeof matchers[key] !== 'undefined') {
          _ref1 = matchers[key];
          for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
            addr = _ref1[_j];
            plugin = plugins[addr];
            handlerFn = plugin[key](node.label[key]);
            handlerFn(node);
          }
        }
      }
    }
    return node;
  }
};
