// Generated by CoffeeScript 1.4.0
var Plugin;

module.exports = Plugin = {
  configure: function(stacker, config) {},
  edge: function(placeholder, nodes) {},
  handles: ['fox', 'dog'],
  fox: function() {},
  dog: function() {}
};
