// Generated by CoffeeScript 1.4.0
var Plugin;

module.exports = Plugin = {
  configure: function(stacker, config) {},
  edge: function(placeholder, nodes) {},
  handles: ['fox', 'dog'],
  fox: function() {},
  dog: function() {},
  matches: ['speed', 'colour', 'disposition'],
  speed: function(value) {
    if (value === 'quick') {
      return Plugin.fox;
    }
  },
  colour: function(value) {
    if (value === 'brown') {
      return Plugin.fox;
    }
  },
  disposition: function(value) {
    if (value === 'lazy') {
      return Plugin.dog;
    }
  }
};
