// Generated by CoffeeScript 1.4.0
var Specification;

Specification = require('./specification');

module.exports = {
  object: {
    set: {
      expect: function(name) {
        return Object.prototype.expect = function() {
          var configuration, edges, key, _results;
          if (!(edges = Specification.getNode(name).edges)) {
            return;
          }
          _results = [];
          for (key in arguments[0]) {
            configuration = {};
            configuration[key] = arguments[0][key];
            _results.push(edges.push(Specification.create(this, configuration)));
          }
          return _results;
        };
      }
    }
  }
};
