// Generated by CoffeeScript 1.4.0
var Specification;

Specification = require('./specification');

module.exports = {
  object: {
    set: {
      expect: function(name) {
        console.log('bind Object.prototype.expect() to', name);
        return Object.prototype.expect = function() {
          var edges;
          if (!(edges = Stack.stacks[name].edges)) {

          }
        };
      },
      expectSet: function(name) {
        console.log('bind Object.prototype.expectSet() to', name);
        return Object.prototype.expectSet = function() {};
      },
      expectGet: function(name) {
        console.log('bind Object.prototype.expectGet() to', name);
        return Object.prototype.expectGet = function() {};
      }
    }
  }
};
