// Generated by CoffeeScript 1.6.3
var collection;

collection = {};

module.exports = {
  get: function(opts, callback) {
    opts || (opts = {});
    if (opts.id == null) {
      throw new Error('realizers.get(opts, callback) opts.id as the realizer id');
    }
    if (collection[opts.id] == null) {
      return callback(new Error('missing realizer'));
    }
  }
};
