// Generated by CoffeeScript 1.4.0
var Realizer;

require('fing');

Realizer = (function() {

  function Realizer() {}

  Realizer.realizers = {};

  Realizer.createFunction = function(name, object, configuration, realization) {
    var key;
    key = object.fing.ref + ':' + name;
    if (typeof this.realizers[key] === 'undefined') {
      this.realizers[key] = {};
    }
    return object[name] = function() {
      return realization();
    };
  };

  return Realizer;

})();

module.exports = Realizer;
