// Generated by CoffeeScript 1.4.0
var Notification, Realization,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Notification = require('./notification');

module.exports = Realization = Realization = (function(_super) {

  __extends(Realization, _super);

  function Realization(object) {
    this.object = object;
  }

  Realization.prototype.createFunction = function(name, opts) {
    this.name = name;
    if (opts == null) {
      opts = {};
    }
  };

  Realization.prototype.createProperty = function(name, opts) {
    this.name = name;
    if (opts == null) {
      opts = {};
    }
  };

  Realization.prototype.realize = function(functionArgs) {
    this.functionArgs = functionArgs;
  };

  return Realization;

})(Notification);
