// Generated by CoffeeScript 1.4.0
var Realizer;

Realizer = (function() {

  function Realizer() {}

  Realizer.realizers = {};

  Realizer.createFunction = function(name, object, realization, configuration) {
    return object[name] = function() {
      return realization();
    };
  };

  return Realizer;

})();

module.exports = Realizer;
