// Generated by CoffeeScript 1.4.0
var Plex, Scaffold;

Plex = require('plex');

module.exports = Scaffold = (function() {

  function Scaffold(label, config, injectable) {
    this.label = label;
    this.config = config;
    this.injectable = injectable;
    if (typeof this.label !== 'string') {
      throw new Error("Scaffold requires 'label' string as arg1");
    }
    if (typeof this.config !== 'object') {
      throw new Error("Scaffold requires config hash as arg2");
    }
    if (typeof this.injectable !== 'function') {
      throw new Error("Scaffold requires injectable function arg3");
    }
  }

  return Scaffold;

})();
