// Generated by CoffeeScript 1.4.0
var Defaults, Plex, Scaffold;

Defaults = require('./defaults');

Plex = require('plex');

module.exports = Scaffold = (function() {

  function Scaffold(label, config, injectable) {
    var abilities, nodeID;
    this.label = label;
    this.config = config;
    this.injectable = injectable;
    this.outerValidate();
    nodeID = process.env.NODE_ID;
    abilities = process.env.NODE_ABILITIES || '';
    this.config._as(nodeID, abilities.split(' '), function(config) {});
  }

  Scaffold.prototype.outerValidate = function() {
    if (typeof this.label !== 'string') {
      throw new Error("Scaffold requires 'label' string as arg1");
    }
    if (typeof this.config !== 'object') {
      throw new Error("Scaffold requires config hash as arg2");
    }
    if (typeof this.config.as === 'undefined') {
      if (typeof this.config._as !== 'function') {
        throw new Error("Scaffold requires behaviour definition in config._as");
      }
    } else {
      if (typeof Defaults[this.config.as] === 'undefined') {
        throw new Error("Scaffold as '" + this.config.as + "' is not defined");
      }
      this.config._as = Defaults[this.config.as];
    }
    if (typeof this.injectable !== 'function') {
      throw new Error("Scaffold requires injectable function arg3");
    }
  };

  return Scaffold;

})();
