// Generated by CoffeeScript 1.4.0
var Expectation, Specification;

Expectation = require('./expectation');

module.exports = Specification = {
  getNode: function(stackName) {
    return require('./nez').stacks[stackName].node;
  },
  create: function(array, opts) {
    var key, _results;
    if (opts == null) {
      opts = {};
    }
    _results = [];
    for (key in opts) {
      if (key === 'expect') {
        continue;
      }
      switch (key) {
        case 'expectation':
          _results.push(array.push(new Expectation(opts[key])));
          break;
        default:
          _results.push(void 0);
      }
    }
    return _results;
  }
};
