// Generated by CoffeeScript 1.4.0
var Confirmation, Specification;

require('fing');

Confirmation = require('./confirmation');

Specification = (function() {

  function Specification() {}

  Specification.objects = {};

  Specification.create = function(object, expectation) {
    var confirmation, _base, _name;
    (_base = this.objects)[_name = object.fing.ref] || (_base[_name] = {
      object: object,
      confirmations: []
    });
    confirmation = new Confirmation(object, expectation, function(realization) {
      console.log('REALIZATION:', realization);
      return console.log('TODO: it this realization back into the Confirmation stack');
    });
    return this.objects[object.fing.ref].confirmations.push(confirmation);
  };

  return Specification;

})();

module.exports = Specification;
