// Generated by CoffeeScript 1.4.0
var Node, Stack,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

require('fing');

Node = require('./node');

module.exports = Stack = (function() {

  Stack.prototype.className = 'Stack';

  function Stack(name) {
    this.name = name;
    this.pusher = __bind(this.pusher, this);

    this.stack = [];
    this.walker = this.tree = [];
  }

  Stack.prototype.pusher = function(label, callback) {
    return this.push(arguments);
  };

  Stack.prototype.push = function(args) {
    var callback, klass, label, node;
    label = args[0];
    callback = args[1];
    klass = this.pendingClass || this.name;
    if (callback && callback.fing.args.length > 0) {
      this.pendingClass = callback.fing.args[0].name;
    }
    if (label) {
      this.node = new Node(label, {
        callback: callback,
        "class": klass
      });
      this.stack.push(this.node);
      this.walker.push(this.node);
      this.walker = this.node.edges;
      if (callback) {
        this.node.callback(this.pusher);
      }
      node = this.stack.pop();
      if (this.stack.length > 0) {
        this.node = this.stack[this.stack.length - 1];
        this.walker = this.node.edges;
      }
      return this.pendingClass = this.node["class"];
    }
  };

  return Stack;

})();
