// Generated by CoffeeScript 1.4.0
var injector;

injector = require('nezkit').injector;

require('fing');

injector.inject(function(Node, _arg) {
  var fixPath, should;
  fixPath = _arg.Link, should = _arg.should;
  Node.should.equal(require('./node'));
  return fixPath('moo').should.equal('moo.coffee');
});
