// Generated by CoffeeScript 1.4.0
var Realizer, Validation;

Realizer = require('./realizer');

Validation = (function() {

  function Validation(expectation) {
    var call, name, object,
      _this = this;
    this.expectation = expectation;
    this.realization = {};
    call = this.expectation.realizerCall;
    name = this.expectation.realizerName;
    object = this.expectation.on;
    Realizer[call](name, object, this.expectation, function(realization) {
      return _this.realization = realization;
    });
  }

  return Validation;

})();

module.exports = Validation;
