// Generated by CoffeeScript 1.4.0
var Validation;

Validation = (function() {

  function Validation(expectation) {
    this.expectation = expectation;
  }

  Validation.prototype.createRealization = function() {
    return function() {
      return 'REALIZATION CALLBACK';
    };
  };

  return Validation;

})();

module.exports = Validation;
