// Generated by CoffeeScript 1.4.0
var Realizer, Validation;

Realizer = require('./realizer');

require('should');

Validation = (function() {

  function Validation(expectation) {
    var call, name, object,
      _this = this;
    this.expectation = expectation;
    this.realization = {};
    call = this.expectation.realizerCall;
    name = this.expectation.realizerName;
    object = this.expectation.on;
    Realizer[call](name, object, this.expectation, function(realization) {
      return _this.realization = realization;
    });
  }

  Validation.prototype.validate = function() {
    var expected, position, realized, received, seq;
    expected = this.expectation["with"];
    realized = this.realization.args;
    if (!(expected && realized)) {
      return;
    }
    received = {};
    for (seq in expected) {
      if (seq === 'expect') {
        continue;
      }
      position = parseInt(seq) - 1;
      if (realized[position]) {
        received[seq] = realized[position];
      }
    }
    return expected.should.eql(received);
  };

  return Validation;

})();

module.exports = Validation;
