// Generated by CoffeeScript 1.6.3
var coffee, error, filename, fs, phrase, program, realizer, realzerFn, recursor;

program = require('commander');

fs = require('fs');

coffee = require('coffee-script');

phrase = require('phrase');

program.version(JSON.parse(fs.readFileSync(__dirname + '/../../package.json', 'utf8')).version);

program.usage('[options] [realizerFile]');

program.parse(process.argv);

try {
  filename = program.args[0];
  if (filename == null) {
    console.log('missing realizerFile');
    process.exit(1);
  }
  realizer = fs.readFileSync(filename, 'utf8');
  if (filename.match(/[coffee|litcoffee]$/)) {
    realizer = coffee.compile(realizer, {
      bare: true
    });
  }
  realizer = eval(realizer);
  realzerFn = realizer.realize || function(Signature) {
    return Signature('Title', function(end) {
      return end();
    });
  };
  delete realizer.realize;
  recursor = phrase.createRoot(realizer, function(token) {
    return token.on('ready', function(_arg) {
      var tokens;
      tokens = _arg.tokens;
      return token.run(tokens['/submarine test/realizer']).then(function(_arg1) {
        var job;
        job = _arg1.job;
        return console.log(job);
      });
    });
  });
  recursor('realizer', realzerFn);
} catch (_error) {
  error = _error;
  console.log(error.message);
  process.exit(2);
}
