// Generated by CoffeeScript 1.4.0
var Dev, fs;

fs = require('fs');

module.exports = Dev = (function() {

  function Dev(program) {
    var app, appdir, libdir;
    this.program = program;
    try {
      libdir = fs.lstatSync('./lib');
    } catch (_error) {}
    try {
      appdir = fs.lstatSync('./app');
    } catch (_error) {}
    if (libdir && libdir.isDirectory) {
      app = './lib';
    }
    if (appdir && appdir.isDirectory) {
      if (app) {
        console.log('Appologies. Supports ./app OR ./lib dirs. Not both.');
        return;
      }
      app = './app';
    }
    this.config = {
      spec: this.program.specdir || './spec',
      src: this.program.srcdir || './src',
      app: app || './app'
    };
  }

  Dev.prototype.start = function() {
    return console.log("running config:", this.config);
  };

  return Dev;

})();
