// Generated by CoffeeScript 1.4.0
var colors, context, program;

program = require('commander');

colors = require('colors');

context = {
  root: function() {
    return program.root || './';
  },
  huh: function() {
    return console.log("\n\n");
  },
  init: function() {},
  status: function() {
    return console.log('running status from root:', context.root());
  },
  pull: function() {},
  push: function() {}
};

program.option('-r, --root [root]', 'Specify the root repo. Default ./');

program.command('huh?').description('Explains more fully the purpose of this tool.').action(function() {
  return context.huh();
});

program.command('init').description('Assemble the initial .git_root control file into [root]').action(function() {
  return context.pull();
});

program.command('status').description('Git status across all nested git repos').action(function() {
  return context.status();
});

program.command('pull').description('Git pull across all nested git repos not up-to-date with .git_root').action(function() {
  return context.pull();
});

program.command('push').description('Git push across all nested git repos pending commits and update .git_root').action(function() {
  return context.push();
});

program.parse(process.argv);
