// Generated by CoffeeScript 1.4.0
var colors, program;

program = require('commander');

colors = require('colors');

program.option('-s, --scan [headRepo]', 'Scan for nested git repos');

program.parse(process.argv);
