// Generated by CoffeeScript 1.4.0
var program;

program = require('commander');

program.option('-d, --dev', 'Run development environment.');

program.parse(process.argv);

module.exports = {
  exec: function() {
    var app, run;
    if (program.dev) {
      run = './dev';
    }
    run = './dev';
    app = new (require(run))(program);
    return app.start();
  }
};
