// Generated by CoffeeScript 1.4.0
var ExecNez, colors, program;

program = require('commander');

colors = require('colors');

program.option('-d, --dev [flavour]', 'Run development environment. [coffee|js]');

program.option('-u, --uplink [hostname]', 'Uplink to your Nimbal instance');

program.option('-n, --noautospec', 'Disable autogeneration of missing specs');

program.parse(process.argv);

module.exports = ExecNez = {
  exec: function(objective, config) {
    console.log('\n' + "(objective) " + objective.bold);
    ExecNez.objective = objective;
    if (!config) {
      return ExecNez.start;
    }
    return ExecNez.start(config);
  },
  start: function(config) {
    var execModules, flavour, hostname, meta, name, _results;
    ExecNez.config = config;
    for (meta in config) {
      if (meta === 'nimbal') {
        continue;
      }
      if (meta === 'description') {
        continue;
      }
      console.log(("(" + meta + ") ") + ExecNez.config[meta].bold);
    }
    console.log(config['description'].bold);
    if (!program.dev) {
      program.dev = true;
    }
    execModules = {};
    if (program.uplink) {
      hostname = 'localhost';
      if (typeof program.uplink === 'string') {
        hostname = program.uplink;
      }
      execModules['./uplink'] = {
        hostname: hostname
      };
    }
    if (program.dev) {
      if (typeof program.dev === 'boolean') {
        flavour = 'coffee';
      } else {
        flavour = program.dev;
      }
      execModules["./dev/" + flavour] = {
        program: program
      };
    }
    _results = [];
    for (name in execModules) {
      _results.push((new (require(name))(execModules[name])).start());
    }
    return _results;
  }
};
