// Generated by CoffeeScript 1.4.0
var Uplink;

module.exports = Uplink = (function() {

  function Uplink(opts) {
    console.log('Uplink to:', opts.hostname);
  }

  Uplink.prototype.start = function() {
    return console.log('Uplink not yet implemented');
  };

  return Uplink;

})();
