// Generated by CoffeeScript 1.4.0
var Requirement;

module.exports = Requirement = {
  configure: function(stacker, config) {},
  edge: function(placeholder, nodes) {},
  handles: ['requirement'],
  requirement: function(node) {
    var meta;
    meta = node.label;
    node.label = meta.title;
    node["class"] = 'requirement';
    return node.requirement = meta;
  },
  matches: ['as'],
  as: function(value) {
    return Requirement.requirement;
  }
};
