// Generated by CoffeeScript 1.4.0

process.on('SIGHUP', require('./plugin_register').hup);

module.exports = {
  objective: require('./objective'),
  realize: require('./realization'),
  linked: function(injectable) {
    return console.log('link not implemented');
  }
};
