// Generated by CoffeeScript 1.4.0
var Tree, trees,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

require('fing');

trees = {};

Tree = (function() {

  function Tree(subscribe) {
    this.edge = __bind(this.edge, this);
    subscribe('edge', this.edge);
  }

  Tree.prototype.edge = function(placeholder, nodes) {
    return this.traverse(nodes.from, nodes.to);
  };

  Tree.prototype.traverse = function(from, to) {
    return console.log("" + from["class"] + " " + from.label, '\t------>\t', "" + to["class"] + " " + to.label);
  };

  return Tree;

})();

module.exports = {
  create: function(stack) {
    var _name;
    return trees[_name = stack.fing.id] || (trees[_name] = new Tree(stack.on));
  }
};
