// Generated by CoffeeScript 1.6.3
var Develop, Objective, Realize, _ref,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Objective = require('../objective/objective');

Realize = require('../realization/realize');

Develop = (function(_super) {
  __extends(Develop, _super);

  function Develop() {
    _ref = Develop.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  Develop.prototype.startMonitor = function(opts, monitor, jobTokens, jobEmitter) {
    var _this = this;
    this.jobTokens = jobTokens;
    this.jobEmitter = jobEmitter;
    monitor.dirs.add(opts.src.directory, opts.src.match, 'src');
    monitor.dirs.on('create', function(filename, stats, ref) {
      if (ref !== 'src') {
        return;
      }
      return _this.handleCreatedSourceFile(filename);
    });
    monitor.dirs.on('change', function(filename, stats, ref) {
      if (ref === 'src') {
        return _this.handleChangedSourceFile(filename);
      } else {
        return _this.handleChangedSpecFile(filename);
      }
    });
    return monitor.dirs.on('delete', function(filename, stats, ref) {
      if (ref !== 'src') {
        return;
      }
      return _this.handleDeletedSourceFile(filename);
    });
  };

  Develop.prototype.onBoundryAssemble = function(opts, callback) {
    return Realize.loadRealizer(opts).then(function(realizer) {
      var phrase;
      phrase = {
        title: realizer.opts.title,
        control: realizer.opts,
        fn: realizer.realizerFn
      };
      delete phrase.control.title;
      return callback(null, phrase);
    }, function(error) {
      return callback(error);
    });
  };

  Develop.prototype.configure = function(opts, done) {
    if (opts.boundry == null) {
      opts.boundry = ['spec', 'test'];
    }
    opts.src || (opts.src = {});
    if (opts.src.directory == null) {
      opts.src.directory = 'src';
    }
    if (opts.src.match == null) {
      opts.src.match = /\.coffee$/;
    }
    return done();
  };

  Develop.prototype.defaultObjective = function(spec) {
    return spec.link({
      directory: 'spec'
    });
  };

  Develop.prototype.handleCreatedSourceFile = function(filename) {
    return console.log({
      created: filename
    });
  };

  Develop.prototype.handleChangedSourceFile = function(filename) {
    return console.log({
      changed: filename
    });
  };

  Develop.prototype.handleDeletedSourceFile = function(filename) {
    return console.log({
      deleted: filename
    });
  };

  Develop.prototype.handleChangedSpecFile = function(filename) {
    console.log({
      SPEC_CHANGE: filename
    });
    return console.log(this.jobTokens);
  };

  return Develop;

})(Objective);

module.exports = Develop;
