// Generated by CoffeeScript 1.6.3
var Controller;

module.exports = Controller = (function() {
  function Controller(opts) {
    console.log({
      DEFAULT_CONTROLLER: opts
    });
  }

  return Controller;

})();
