// Generated by CoffeeScript 1.6.3
var Notice, async, ipso, tools;

Notice = require('notice');

async = require('also').inject.async;

tools = require('../tools');

ipso = require('ipso');

module.exports = function(title, optionalOpts, realizerFn) {
  var context, realizer, _ref;
  _ref = ipso.validate.apply(this, arguments), context = _ref.context, realizerFn = _ref.realizerFn;
  context.tools = tools;
  realizer = async({
    beforeAll: function(done, inject) {
      return Notice.connect('realizer', context, function(error, notice) {
        inject.first[0] = context;
        inject.first[1] = notice;
        return done();
      });
    }
  }, ipso);
  return realizer(realizerFn);
};
