// Generated by CoffeeScript 1.6.3
var ipso;

ipso = require('ipso');

module.exports = function(title, fn) {
  console.log('START REALIZER');
  return console.log(JSON.stringify({
    realize: {
      transport: process.env['OBJECTIVE_transport'],
      address: process.env['OBJECTIVE_address'],
      port: process.env['OBJECTIVE_port'],
      title: title
    }
  }, null, 2));
};
