// Generated by CoffeeScript 1.6.3
exports.createCollection = function(ƒ) {
  var π;
  return new ((function() {
    try {
      if (ƒ.controller != null) {
        return require(ƒ.controller);
      } else {
        return require('./controller');
      }
    } catch (_error) {
      π = _error;
      try {
        delete ƒ.listen.secret;
      } catch (_error) {}
      try {
        delete ƒ.listening;
      } catch (_error) {}
      console.log({
        OPTS: ƒ,
        ERROR: π
      });
      return process.exit(4);
    }
  })())(ƒ);
};
